[tool.poetry]
name = "supermarket"
version = "0.1.0"
description = ""
authors = ["Filipe Port <filipeportt@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
